---
title: "R Notebook"
output: html_notebook
---

```{r}
# Get current working directory
current_dir <- getwd()
print(current_dir)

# List files in current directory
files_in_dir <- list.files()
print(files_in_dir)
```
```{r}
options(java.parameters="-Xmx2g")
library("dfrtopics")
library("dplyr")
library("ggplot2")
library("lubridate")
library("stringr")
```

```{r}
install.packages("remotes")
```
```{r}
remotes::install_github("agoldst/dfrtopics")
```
```{r}
library(dfrtopics)
```

```{r}
# Provide the full file path
full_file_path <- "/Users/avah/Desktop/mallet/preprocessed_text.txt"

# Read  contents of the text file into character vector
text_data <- readLines(full_file_path)

# Convert character vector to a corpus
library(tm)
corpus <- Corpus(VectorSource(text_data))

# Perform further text processing, create Document-Term Matrix (DTM)

corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removeWords, stopwords("en"))
dtm <- DocumentTermMatrix(corpus)

# Inspect DTM
inspect(dtm)
```
```{r}
## trying out creating the corpus with mallet on r


# Install and load required packages
install.packages("tm")
install.packages("mallet")

library(tm)
library(mallet)

# Set path to mallet binary
mallet_path <- "/Users/avah/Desktop/mallet/bin"

# Function to preprocess text
preprocess_text <- function(text) {
  # Return the preprocessed text
  return(text)
}

# PubMed search term
search_term <- "(((mood) OR (depress*) OR (affective disorder)) OR ((psychosis) OR (schizo*) OR (psychotic))) AND ((psychedelic) OR (hallucinogen) OR (entheogen) OR (hallucinogenic) OR (psychotropic)) AND (2014/2024[Date - Publication])"

# Preprocess the text data
corpus <- sapply(articles$text, preprocess_text)

# corpus from preprocessed text
corpus <- Corpus(VectorSource(corpus))

# Clean corpus
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removeWords, stopwords("en"))
corpus <- tm_map(corpus, stripWhitespace)

# Convert corpus to document-term matrix
dtm <- DocumentTermMatrix(corpus)

# Convert document-term matrix to matrix for mallet
mallet_dtm <- as.matrix(dtm)

# Train LDA model using mallet
num_topics <- 20
lda_model <- MalletLDA(num_topics)
lda_model$loadDocuments(mallet_dtm)
lda_model$train(100)

# Print topics
topics <- topics(lda_model, n=10)
print(topics)
```